config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'products#index'
  delete 'session' => 'products#destroy_gallery'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :product
  #has_many :photos, :dependent => :destroy
  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :galleries, :dependent => :destroy
	accepts_nested_attributes_for :galleries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.create(product_params)
    respond_to do |format|
      if @product.save
        if params[:photos]
        params[:photos].each { |photo|
          @product.galleries.create(photo: photo)
        }
      end
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
          if params[:photos]
          params[:photos].each { |photo|
            @product.galleries.create(photo: photo)
          }
        end
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    if params[:gallery] == 'true'
    destroy_gallery(params[:gal_id])
    else
      @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end


  def destroy_gallery(gallery_id)
    @gallery = Gallery.where(id: gallery_id).first
    @gallery.destroy
    respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, galleries_attributes: [:photo, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductsGallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <p class="navbar-text navbar-left">
            <%= link_to "Items", root_path, class: "btn btn-default"  %>
          </p>
          <p class="navbar-text navbar-left">
            <%= link_to 'New Item!', new_product_path, class: "btn btn-default"  %>
          </p>
        </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>

app/views/products/_form.html.erb
<%= nested_form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div><br>
  <div id="dropzone" class="fade">Drop files here</div><br>
  <%= file_field_tag "photos[]", type: :file, multiple: true, name: 'photo<div class="entry-thumbnail" data-picture="" data-alt=""><img src="" alt=""></div>' %>
    <div class="actions"><br>
  </div>
  <div class="progress-wrapper">
    <p>Bitrate: <span class="bitrate"></span></p>
    <div class="progress">
      <div class="progress-bar" role="progressbar">
        0%
      </div>
    </div>
  </div>
  <%= f.submit %>
<% end %>

<script>
  $(document).ready(function() {
    var multiple_photos_form = $('#new_product');
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var bitrate = wrapper.find('.bitrate');
    var progress_bar = wrapper.find('.progress-bar');

    multiple_photos_form.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'),
      add: function (e, data) {
        types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
        }
        else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
      }
    });

    multiple_photos_form.on('fileuploadstart', function() {
      wrapper.show();
    });

    multiple_photos_form.on('fileuploaddone', function() {
      wrapper.hide();
      progress_bar.width(0);
    });

    multiple_photos_form.on('fileuploadsubmit', function (e, data) {
      data.formData = {'photo[author]': $('#photo_author').val()};
    });

    multiple_photos_form.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });

    $(document).bind('dragover', function (e) {
      var dropZone = $('#dropzone'),
              timeout = window.dropZoneTimeout;
      if (!timeout) {
        dropZone.addClass('in');
      } else {
        clearTimeout(timeout);
      }
      var found = false,
              node = e.target;
      do {
        if (node === dropZone[0]) {
          found = true;
          break;
        }
        node = node.parentNode;
      } while (node != null);
      if (found) {
        dropZone.addClass('hover');
      } else {
        dropZone.removeClass('hover');
      }
      window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
      }, 100);
    });
  });
</script>

app/views/products/_gallery.html.erb
<% @product.galleries.each do |gallery| %>

  <div class="col-lg-9">
    <%= image_tag gallery.photo.url(:small), class: "thumb" %><br/>
    <%= link_to "Delete Gallery", product_path(@product, gallery: 'true', gal_id: gallery.id), method: :delete %>
  </div>
  <br/>
<% end %>

app/views/products/create.js.erb
<% if @product.new_record? %>
  alert('Failed');
<% else %>
  if ($('h1') !== undefined) {
    $('h1').append("<%=j render partial: 'products/product', locals: { product: @product } %>");
  }
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<br />
<%= render 'gallery' %>
<br />
<br>
<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<p id="notice"><%= notice %></p>

<% @products.each do |product| %>
  <div class="row" id="recipe_top">
    <div class="col-md-12">
      <h2><%= link_to product.name, product %></h2>
      <p>
        <% product.galleries.each do |gallery| %>
          <% if gallery.photo.exists? %>
            <%= image_tag gallery.photo.url(:small) %><br/>
          <% end %>
        <% end %>
      </p>
      <p><%= "#{time_ago_in_words(product.created_at)} ago" %></p>
      <p><%= product.price %></p>
      <p><%= product.description %></p>
      <br>
      <%= link_to 'Show', product, class: "btn btn-default"  %>
      <%= link_to 'Edit', edit_product_path(product), class: "btn btn-default"  %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"  %>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', products_path, class: "btn btn-default"  %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<br />

<%= render 'gallery' %>
<br />
<br>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

<%= @gallery %>